name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'  # Replace with the Flutter version you are using

      - name: flutter upgrade
        run: flutter upgrade
        
      - name: Install dependencies
        run: flutter pub get

      - name: Build and analyze with SonarCloud
       - name: Run Dart Analyzer with SonarQube output
        run: |
          pub global activate dart_style
          pub global activate coverage
          pub global activate melos
          melos bootstrap
          melos run dartanalyzer --no-pub --no-to-json --format sonarqube

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
